# Generated by Django 5.1.1 on 2024-11-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='username',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
