# Generated by Django 5.1.1 on 2024-11-13 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_category_tb_covertype_tb_product_tb'),
        ('customer', '0002_customer_tb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.product_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_tb')),
            ],
        ),
    ]
