# Generated by Django 5.1.1 on 2024-11-14 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postel_code', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('order_date', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('order_totle', models.IntegerField()),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('tracking', models.CharField(blank=True, max_length=50)),
                ('shiping_date', models.CharField(blank=True, max_length=50)),
                ('transactionid', models.CharField(blank=True, max_length=50)),
                ('paymentduedate', models.CharField(blank=True, max_length=50)),
                ('paymentstatus', models.CharField(default='pending', max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_tb')),
            ],
        ),
    ]
