# Generated by Django 5.1.1 on 2024-11-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_order_totle_order_tb_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_tb',
            name='order_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
