# Generated by Django 5.1.1 on 2024-11-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_category_tb_covertype_tb_product_tb'),
        ('customer', '0006_alter_order_tb_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order_tb')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.product_tb')),
            ],
        ),
    ]
