# Generated by Django 5.1.1 on 2024-11-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_tb',
        ),
    ]
