# Generated by Django 5.1.1 on 2024-11-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_admin_admin_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_tb',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
