# Generated by Django 5.1.1 on 2024-11-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_admin_tb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='covertype_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('listprice', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('price50', models.PositiveIntegerField()),
                ('price100', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.category_tb')),
                ('covertypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.covertype_tb')),
            ],
        ),
    ]
